version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD:  "postgres"
      POSTGRES_DB: "app"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

networks:
  default:
    external: true
    name: grpc-inventory-default